 using DAEDALUS07.Client.Rendering;
 using DAEDALUS07.Core.Entities;
 using DAEDALUS07.Core.Generation;
 using DAEDALUS07.Core.Grid;
 using SadConsole;                                                                                                                                                                                                                            
    using SadConsole.Configuration;                                                                                                                                                                                                              
                                                                                                                                                                                                                                                 
    Settings.WindowTitle = "DAEDALUS-07 // SYSTEM INFILTRATION";                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
    Builder configuration = new Builder()                                                                                                                                                                                                        
        .SetWindowSizeInCells(100, 35)                                                                                                                                                                                                           
        .OnStart(Startup);                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                 
    Game.Create(configuration);                                                                                                                                                                                                                  
    Game.Instance.Run();                                                                                                                                                                                                                         
    Game.Instance.Dispose();                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                 
    void Startup(object? sender, GameHost host)                                                                                                                                                                                                  
    {                                                                                                                                                                                                                                                        
         SubnetGrid grid = new(80, 25);                                                                                                                                                                                                               
                                                                                                                                                                                                                                                
    var (rooms, spawn) = BspDungeonGenerator.Generate(grid, minSize: 6, maxSplits: 4, new Random());                                                                                                                                             
                                                                                                                                                                                                                                                
    Entity player = new(spawn.x, spawn.y, "THESEUS");                                                                                                                                                                                            
                                                                                                                                                                                                                                                 
    SubnetRenderer renderer = new(grid, player);                                                                                                                                                                                                 
    Game.Instance.Screen = renderer;                                                                                                                                                                                                              
    }   